### ISSUE TITLE
I have 4.3 Nextion

### ISSUE THREAD

**Issue by Jermano75** [Andoramb/OHMARDNEX#1]
On nextion editor how can i use so it fits the 4.3 nextion display, becouse when i try to upload it says p0 size not correct and was made for a diferent screen. 
how can i a use for this 4.3 display and can i use arduino uno or ft232rl ft232 ftdi usb 3.3v 5.5v  to pass the data ?

**Comment by Andoramb** [comment]
The project was made for 3.5 size, but it can be converted to 4.5
Make sure to have this project/device selected as the image:
![image](https://user-images.githubusercontent.com/3399628/118867933-e8ef0e80-b8e3-11eb-9359-035af9be7078.png)

Then have it rotated to '90 Horizontal' position.
The page layout will be different, so you'll need to resize, but it should work, if you have 'that specific' display type

**Comment by Jermano75** [comment]
Thanks in advance for the help :), i will test it and leave it here what where the progress

**Comment by Andoramb** [comment]
@Jermano75 any updates?

**Comment by JeanDaBleaque** [comment]
You can use Arduino UNO w/ software serial. You can feed nextion screens directly with UNO's 5V output. I am using without any major problems. Also I recreated nextion file to fit 240*320 (w/h) screen. All images in this projects directly scaled to 240*320 screen size. Some animation frames deleted, fonts reduced. I don't know what is problem but sometimes program doesn't sends hardware info's correctly. I tried to rebuild the whole project but didn't found any solutions yet. I'll share solution when i found it. If anyone uses 2.4 inch nextion screen i can share hmi file.

**Comment by Andoramb** [comment]
@JeanDaBleaque yes, that's how it's intended to be 😁👍
Strange that it's not sending the info. can you give some examples? no info at all? do you run the app with admin rights?

**Comment by JeanDaBleaque** [comment]
Yep yes i'm running program with admin rights. Actually sometimes program sends pc hardware info after de-checking/checking check boxes and starting serial communication again. Sometimes program just sends cpu/gpu/ram/hdd informations without mainboard information, sometimes not sending anything to stats 2 menu. I am currently working on color palette addition for my strip rgb leds. I'll look to solve this problem when i finish it.
Edit: https://imgur.com/5vbtFCS

**Comment by Andoramb** [comment]
I was also looking for a way to add rgb light control (hence the rgb page) for Mystic light (MSI) or iCue (Corsair) or NZXT or whatever... but I find it too time-consuming to implement all these things. do you have a solution/idea for that?
as for the hw info... maybe a delay could fix it

**Comment by JeanDaBleaque** [comment]
Program sends hardware informations once probably that's the problem. I'll try sending hardware information periodically. I added RGB Led Settings to the program for my strip leds. (for WS2812B) https://imgur.com/kndlBf5
I am also sending 16 bit color data to nextion for the rgb menu.

**Comment by Andoramb** [comment]
Closed due to inactivity
