### ISSUE TITLE
editing c# code

### ISSUE THREAD

**Issue by Buurte** [Andoramb/OHMARDNEX#3]
i wanted to edit some things in your code but it seems it is blocked in visual studio, when i want to build the code

**Comment by Andoramb** [comment]
Hi, how do you mean blocked?

**Comment by katexz** [comment]
Hello, I really liked your code but I want different things and I want it to run as administrator and connect automatically when windows starts, so I tried to play with the code but it gave an error about clickonce. If you know the solution, can you share it with me? I am very new to c# coding.

**Comment by Andoramb** [comment]
Hey @katexz, sorry for the late reply, let me have a look at this

**Comment by Andoramb** [comment]
Could you checkout the [autostart branch](https://github.com/Andoramb/OHMARDNEX/tree/autostart)?
Let me know if it works out for you!
